/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDonation } from "./IDonation";
export type { IRewardPool } from "./IRewardPool";
export type { IStaking } from "./IStaking";
