/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRewardPool,
  IRewardPoolInterface,
} from "../../../contracts/Interfaces/IRewardPool";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenAddress",
            type: "address",
          },
          {
            internalType: "bool",
            name: "hasLockPeriod",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "unlocksAt",
            type: "uint256",
          },
          {
            internalType: "enum LockPeriod",
            name: "lockPeriod",
            type: "uint8",
          },
        ],
        internalType: "struct RewardData",
        name: "rewardData",
        type: "tuple",
      },
    ],
    name: "addRewardToPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "getRewardPerCycle",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferRewardToUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRewardPool__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardPoolInterface {
    return new Interface(_abi) as IRewardPoolInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRewardPool {
    return new Contract(address, _abi, runner) as unknown as IRewardPool;
  }
}
